In [1]:
import numpy as np
from quantfreedom.enums import CandleBodyType
from quantfreedom.helper_funcs import dl_ex_candles
from quantfreedom.indicators.tv_indicators import *
from quantfreedom.plotting.plotting_base import *

np.set_printoptions(formatter={"float_kind": "{:0.2f}".format})

%load_ext autoreload
%autoreload 2

In [2]:
candles = dl_ex_candles(
    exchange="binance_us",
    symbol="BTCUSDT",
    timeframe="30m",
    candles_to_dl=300,
)

In [3]:
timestamp = candles[:, CandleBodyType.Timestamp]
close = candles[:, CandleBodyType.Close]

In [4]:
sma = sma_tv(source=close,length=20)
sma

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, 45458.78, 45435.32, 45404.67,
       45373.76, 45323.93, 45291.52, 45258.26, 45219.87, 45185.37,
       45169.90, 45151.04, 45136.06, 45107.56, 45073.49, 45037.33,
       45030.71, 45040.49, 45047.93, 45055.85, 45050.40, 45054.16,
       45070.03, 45076.08, 45079.24, 45101.22, 45108.80, 45125.83,
       45150.03, 45174.38, 45171.37, 45177.07, 45186.72, 45205.54,
       45225.52, 45244.25, 45246.11, 45212.20, 45145.38, 45004.60,
       44887.22, 44755.20, 44616.75, 44467.80, 44317.35, 44173.83,
       44065.94, 43972.99, 43861.43, 43735.18, 43628.56, 43510.61,
       43366.14, 43230.68, 43095.00, 42968.25, 42846.23, 42762.59,
       42710.23, 42719.56, 42712.02, 42718.30, 42733.60, 42765.57,
       42799.44, 42814.10, 42798.82, 42770.16, 42775.03, 42787.16,
       42797.90, 42815.15, 42858.64, 42881.11, 42907.86, 42927.43,
       42947.24, 42957.63, 42951.45, 42964.38, 42968.73, 

In [5]:
plot_sma(candles=candles,indicator=sma)

In [6]:
rsi = rsi_tv(
    source=close,
    length=14,
)
rsi

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, 45.31, 38.62, 43.94, 44.44, 50.28, 45.60, 40.58, 44.94, 45.44,
       39.31, 44.26, 42.69, 39.12, 40.14, 48.21, 46.94, 45.03, 44.80,
       44.65, 42.85, 51.13, 52.42, 55.96, 56.69, 54.17, 54.27, 54.90,
       52.89, 51.16, 55.08, 49.94, 54.48, 53.36, 54.74, 43.87, 48.82,
       48.90, 55.38, 56.01, 52.13, 48.61, 31.10, 23.77, 14.06, 23.35,
       21.53, 20.87, 19.37, 18.97, 24.67, 36.64, 43.43, 39.12, 36.57,
       38.59, 37.49, 32.44, 38.44, 38.66, 40.21, 40.35, 42.15, 43.89,
       40.70, 42.00, 41.79, 43.39, 45.16, 44.52, 41.69, 41.60, 45.68,
       52.27, 49.57, 51.78, 52.41, 52.31, 50.41, 53.17, 51.48, 51.86,
       48.79, 41.89, 47.31, 44.34, 49.48, 49.35, 43.32, 51.70, 52.76,
       53.88, 55.09, 59.19, 55.54, 58.06, 57.47, 65.11, 73.41, 72.57,
       63.88, 65.19, 67.61, 63.91, 63.80, 65.90, 71.58, 58.38, 60.13,
       61.24, 65.87, 65.13, 66.15, 63.07, 61.75, 56.37, 58.08, 57.40,
       48.47,

In [7]:
plot_rsi(
    candles=candles,
    indicator=rsi,
)

In [8]:
ema = ema_tv(source=close, length=50)
ema

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 45158.89,
       45158.97, 45165.89, 45173.25, 45176.81, 45176.83, 45150.48,
       45104.19, 45002.73, 44920.93, 44830.99, 44740.26, 44643.01,
       44546.81, 44463.74, 44407.21, 44369.23, 44317.15, 44256.97,
       44203.91, 44148.85, 44075.23, 44018.41, 43964.35, 43915.90,
       43869.67, 43828.98, 43793.45, 43750.70, 43712.10, 43674.48,
       43641.10, 43612.04, 43582.84, 43549.06, 43516.41, 43490.89,
       43477.08, 43459.35, 43445.99, 43434.19, 43422.71, 43409.10,
       43399.91, 43388.95, 43378.92, 43365.63, 43343.42, 43328.45,
       43309.83, 43298.32, 43287.11, 43267.98, 43260.61, 43255.07,
       43251.35, 43249.44, 43253.59, 43253.58, 43257.19, 43260.04,
       43274.94, 43308.86, 43340.56, 43361.24, 

In [9]:
plot_ema(candles=candles, indicator=ema)

In [10]:
sm_hist, sqz_on, no_sqz = squeeze_momentum_lazybear_tv(
    candles=candles,
    length_bb=14,
    length_kc=14,
    multi_bb=2,
    multi_kc=2,
)

In [11]:
plot_squeeze_mom_lazybear(
    candles=candles,
    indicator=sm_hist,
)